### ISSUE TITLE
DOCS: Add a hint for additional JavaScript

### ISSUE THREAD

**Issue by grebaldi** [gerdemann/Gerdemann.ReCAPTCHA#1]
Hi @gerdemann,

I've noticed, that via https://github.com/gerdemann/Gerdemann.ReCAPTCHA/blob/master/Resources/Private/Fusion/Root.fusion two additional JavaScripts are injected to every page.

It is of course easy to add a condition for an inidividual use case, so these scripts only show up on pages, that contain a form. But it would be nice to have a hint to this mechanism in the README, so that dependant developers don't get surprised by this.

**Comment by gerdemann** [comment]
Hi @grebaldi,

Thank you for the feedback. I added a hint in the README.
